[mdb]
url="postgres://postgres/db?sslmode=disable&user=postgres"

[test]
url-template="postgres://db/%s?sslmode=disable&user=postgres"
debug-sql=false

[events]
handlers=["logger"]
emitter-size=1024

[authentication]
enable=true
issuer="https://accounts.kbb1.com/auth/realms/main"

[permissions]
enable=true
log=true
