[server]
bind-address=":8080"
mode="debug"  # GIN mode. Either debug, release or test
rollbar-token=""
rollbar-environment="development"

[mdb]
url="postgres://postgres/mdb?sslmode=disable&user=postgres"

[test]
url-template="postgres://mdb/%s?sslmode=disable&user=postgres"
debug-sql=false

[events]
handlers=["logger"]
emitter-size=1024

[authentication]
enable=true
issuer="https://accounts.kbb1.com/auth/realms/main"

[permissions]
enable=true
log=true
